# Standards: 1.0.0
---

- name: Restart sshd
  systemd:
    name: sshd
    state: restarted
  when: not in_container

- name: Restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
  when: not in_container

- name: Restart auditd
  systemd:
    name: auditd
    state: restarted
  when: not in_container
