# Standards: 1.0.0
---

# 1.1.8 Ensure nodev option set on /var/tmp partition

- name: 1.1.8 - Ensure nodev option set on /var/tmp partition
  mount:
    name: "{{ item.mount }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
    opts: "{{ item.options.split(',') | union(['nodev']) | join(',') }}"
  when: item.mount == '/var/tmp'
  with_items: "{{ ansible_mounts }}"
  tags:
    - level-1
    - section-1
    - section-1.1
    - section-1.1.8
    - "1.1.8"
    - scored
