# Standards: 1.0.0
---

# 1.1.4 Ensure nosuid option set on /tmp partition

- name: 1.1.4 - Ensure nosuid option set on /tmp partition
  mount:
    name: "{{ item.mount }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
    opts: "{{ item.options.split(',') | union(['nosuid']) | join(',') }}"
  when: item.mount == '/tmp'
  with_items: "{{ ansible_mounts }}"
  tags:
    - level-1
    - section-1
    - section-1.1
    - section-1.1.4
    - "1.1.4"
    - scored
