# Standards: 1.0.0
---

# 1.7.1.5 Ensure permissions on /etc/issue are configured

- name: 1.7.1.5 - Ensure permissions on /etc/issue are configured
  file:
    path: "/etc/issue"
    owner: root
    group: root
    mode: 0644
  tags:
    - level-1
    - section-1
    - section-1.7
    - section-1.7.1
    - section-1.7.1.5
    - "1.7.1.5"
    - scored
