# Standards: 1.0.0
---

# 2.1.17 Ensure rsh server is not enabled

- name: 2.1.17 - Ensure rsh server is not enabled
  systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
  with_items:
    - rexec
    - rlogin
    - rsh
  register: systemd
  failed_when: systemd is failed and not 'Could not find the requested service' in systemd.msg
  when: not in_container
  tags:
    - level-1
    - section-2
    - section-2.1
    - section-2.1.17
    - "2.1.17"
    - scored
